name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          zip \
          unzip \
          openjdk-11-jdk \
          build-essential \
          git \
          python3-dev \
          libffi-dev \
          libssl-dev
        
    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install buildozer cython
        
    - name: Setup Android environment
      run: |
        # Устанавливаем Android Command Line Tools
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        mkdir -p android-sdk
        unzip -q commandlinetools-linux-9477386_latest.zip -d android-sdk
        mkdir -p android-sdk/cmdline-tools/latest
        mv android-sdk/cmdline-tools/* android-sdk/cmdline-tools/latest/
        
        # Устанавливаем переменные окружения
        echo "ANDROID_HOME=$PWD/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=$PWD/android-sdk" >> $GITHUB_ENV
        echo "PATH=$PWD/android-sdk/cmdline-tools/latest/bin:$PWD/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV
        
        # Принимаем лицензии и устанавливаем компоненты
        yes | android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"
        android-sdk/cmdline-tools/latest/bin/sdkmanager "cmake;3.22.1" "ndk;25.1.8937393"
        
    - name: Build APK with Buildozer
      run: |
        # Настраиваем Buildozer для использования нашей SDK
        export ANDROIDSDK="$ANDROID_HOME"
        export ANDROIDNDK="$ANDROID_HOME/ndk/25.1.8937393"
        export ANDROIDAPI="33"
        export NDKAPI="21"
        
        buildozer -v android debug
      timeout-minutes: 45
      env:
        ANDROID_HOME: ${{ github.workspace }}/android-sdk
        ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: bin/*.apk
        retention-days: 1
